# Generated by Django 2.2 on 2019-04-25 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departament',
            new_name='Department',
        ),
    ]
